global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-worker'
    static_configs:
      - targets: ['go-worker:9091']

  - job_name: 'go-reaper'
    static_configs:
      - targets: ['go-reaper:9093']

  - job_name: 'python-api'
    static_configs:
      - targets: ['python-api:8000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node-exporter'
    static_configs:
      # NOTE: Remember to use your actual IP here
      - targets: ['10.61.61.146:9100']
